services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - OLLAMA_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    depends_on:
      - db
#      - ollama
    restart: unless-stopped

  db:
    image: postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/db/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?sslmode=disable
      - up

#  ollama:
#    image: ollama/ollama
#    ports:
#      - "11434:11434"
#    volumes:
#      - ollama:/root/.ollama
#    restart: unless-stopped

volumes:
  pgdata:
#  ollama: